# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-28 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0002_auto_20180328_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='univ',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
