# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-28 19:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0003_auto_20180328_1744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='intansi',
            new_name='instansi',
        ),
    ]
