# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-07 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0006_user_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_about', models.TextField(null=True)),
                ('text_alamat', models.CharField(max_length=100, null=True)),
                ('text_no_hp', models.CharField(max_length=40, null=True)),
                ('text_email', models.EmailField(max_length=30, null=True)),
            ],
        ),
    ]
