# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-14 18:17
from __future__ import unicode_literals

import alumni.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0011_articleclip_konten'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='jawaban1',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='jawaban2',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pertanyaan1',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pertanyaan2',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=alumni.models.get_image_path),
        ),
    ]
