# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-15 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0012_auto_20180414_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pekerjaan',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='tahun_aktif',
            field=models.TextField(null=True),
        ),
    ]
