# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-15 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0013_auto_20180415_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='alamat',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
