# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-18 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0016_articleclip_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleclip',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='articleclip',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
