# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-19 01:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0017_auto_20180418_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleclip',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articleclip',
            name='published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='articleclip',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
