# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-19 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0019_auto_20180419_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleclip',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='articleclip',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
