# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-19 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0020_auto_20180419_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleclip',
            name='thumbnail',
            field=models.ImageField(default='article-thumbnails/not-available.jpg', upload_to='article-thumbnails/'),
        ),
    ]
