# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-23 19:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0023_token'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Token',
            new_name='UmToken',
        ),
    ]
