# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-23 20:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0024_auto_20180424_0220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='umtoken',
            name='user',
        ),
        migrations.DeleteModel(
            name='UmToken',
        ),
    ]
