# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-23 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0026_umtoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UmToken',
        ),
        migrations.AlterField(
            model_name='about',
            name='text_email',
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='kota',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
