# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-23 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0027_auto_20180424_0310'),
    ]

    operations = [
        migrations.CreateModel(
            name='UmToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
