# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-25 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0029_auto_20180424_0317'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleclip',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
